#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config top_padding     11
yabai -m config bottom_padding  11
yabai -m config left_padding    11
yabai -m config right_padding   11
yabai -m config window_gap      11

yabai -m config layout bsp
yabai -m config auto_balance on
yabai -m config mouse_follows_focus autoraise

echo "yabai configuration loaded.."
